on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Clone
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: yarn install
      - name: Test
        run: npm run test
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
