on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.11
      - name: Install project dependencs
        run: pnpm i
      - name: Setup .npmrc # publish 用户
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> "$HOME/.npmrc"
      - name: Create Release Pull Request # 1. 在远程执行 changesets version 消费变更集 2. 然后创建一个 pull request 3. 当你 merge request 时候会去执行 npx changeset publish 发版
        uses: changesets/action@v1
        with:
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# # 单仓库 直接发包
# on:
#   push:
#     tags: # Sequence of patterns matched against refs/tags
#       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Publish
#         run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#       - name: Create Release # 通过 GitHub 右侧Release API创建发布操作
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: Release ${{ github.ref }}
#           draft: false
#           prerelease: false
